### ISSUE TITLE
请问Elixir Liveview论坛怎么没有继续呢？

### ISSUE THREAD

**Issue by chenge** [Hentioe/ex_weekly#3]
感觉LV不错。国内目前缺少一个专门的Elixir论坛。

**Comment by Hentioe** [comment]
现在没时间精力啊，哈哈哈

**Comment by chenge** [comment]
跑起来看看效果，维护我可以帮忙，怎么样？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hentioe/ex_weekly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月23日(星期天) 晚上9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hentioe/ex_weekly] 请问Elixir Liveview论坛怎么没有继续呢？ (#3)





 
现在没时间精力啊，哈哈哈

**Comment by Hentioe** [comment]
可以的，可以到我的群里边交流。tg 群：https://t.me/elixir_cn qq 群：912763380
